### PR TITLE
Russian localisation

### PR DESCRIPTION
**Pull request by ingumsky**
Added Russian localisation via extra messages.json file in ru folder.

### CODE REVIEW

**Comment by qunash** [comment]
Thanks for the PR! Could you also translate the strings in [localizedStrings.json](https://github.com/qunash/chatgpt-advanced/blob/main/src/util/localizedStrings.json)? It would be great to have the entire app fully localized in Russian.

**Comment by ingumsky** [comment]
Yep. Will do.

**Comment by ingumsky** [comment]
Added the missing strings.

**Comment by qunash** [comment]
Awesome

**Pull request merged**
